package idea.fuel_payment.gas_service.kafka.dto;

public enum StepAction {
	CREATE_ORDER,
	CHECK_BALANCE,
	ACTIVATE_PUMP,
	WAIT_PUMP_COMPLETE,
	PROCESS_PAYMENT,
	UPDATE_INVENTORY,
	COMPLETE_ORDER,
	SEND_NOTIFICATION,
	CANCEL_ORDER,
	DEBIT_SUPPORT,
	DEACTIVATE_PUMP,
	ROLLBACK_INVENTORY
}
